# Generated by Django 5.0.2 on 2024-02-21 01:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guild",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="guildmasjidsettings",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
