# Generated by Django 5.0.2 on 2024-02-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("discord_", "0002_alter_guild_id_alter_guildmasjidsettings_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="guildmasjidsettings",
            unique_together={("guild", "masjid_data")},
        ),
    ]
