# Generated by Django 5.0.2 on 2024-02-21 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord_", "0004_masjiddata_iqama_source_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masjiddata",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="IqamaTime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("adhan_fajr", models.TimeField()),
                ("iqama_fajr", models.TimeField()),
                ("adhan_dhuhr", models.TimeField()),
                ("iqama_dhuhr", models.TimeField()),
                ("adhan_asr", models.TimeField()),
                ("iqama_asr", models.TimeField()),
                ("adhan_maghrib", models.TimeField()),
                ("iqama_maghrib", models.TimeField()),
                ("adhan_isha", models.TimeField()),
                ("iqama_isha", models.TimeField()),
                (
                    "masjid_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discord_.masjiddata",
                    ),
                ),
            ],
            options={
                "unique_together": {("masjid_data", "date")},
            },
        ),
    ]
